### ISSUE TITLE
printing gets cut

### ISSUE THREAD

**Issue by myrrien** [PhilMurwin/PokemonChecklists#42] opened 2017-12-03 09:52 UTC
hello, I noticed that if I try to print the list it gets cut at page 14, missing some parts. Happens only in portrait mode.

**Comment by PhilMurwin** [comment] 2017-12-04 15:58
Thanks for the heads up, I believe I know what the issue is and I'm working on a fix. :)

**Comment by PhilMurwin** [comment] 2017-12-04 16:45
I think this is now fixed.  For me the Ultra Sun & Moon page prints at 20 pages.  I was seeing some weird cutoffs of letters at the bottom of pages.

If you're still having issues could you please mention the following:
* What checklist you're printing
* What browser you're using
* If you have all sections open, closed, or a mix (assuming you're trying to print the Ultra Sun & Moon list).

**Comment by myrrien** [comment] 2017-12-04 18:29
still printing 14 pages, USUM checklist, Chrome 62.0.3202.94 on W10, all sections open, tried to delete cookies and force hard reloading (ctrl+shift+R), list gets cut at "get a legendary ally on your side" from sub events dropdown. I haven't had the time to look at your code but I have the feeling there's something related to printing in your css since printing in landscape mode gives no issues.

**Comment by PhilMurwin** [comment] 2017-12-04 19:13
I was able to duplicate the issue in Chrome, I'll have to do some research/digging to see what's causing the problem.  Thanks for the heads up.

**Comment by PhilMurwin** [comment] 2017-12-11 17:19
I believe I've found the issue; it looks like the bootstrap framework that I use for the site doesn't reduce for printing all that well in chrome.  It looks like bootstrap defaults to the small setting for printing; I'm working on a custom print.css that should help with the issues.  Hopefully I'll find time to work on that this week yet.

**Comment by PhilMurwin** [comment] 2017-12-11 18:57
Okay, second times a charm.  I think the new fix is working.  It looks like in Chrome it prints at 15 pages and at a glance everything appears to be there where as before it was definitely getting cutoff at a certain point.

**Comment by PhilMurwin** [comment] 2017-12-27 03:44
Pretty confident this issue has been resolved.  Closing the issue; if anyone sees additional printing issues please go ahead and open a new issue describing what is happening.

**Closed by PhilMurwin** 2017-12-27 03:44 UTC
Labels: bug
